### ISSUE TITLE
ImportError: No module named daemon_tree

### ISSUE THREAD

**Issue by Nic2012** [emlid/pywificontrol#14]
Using latest Raspbian Stretch on a Pi Zero, after installing dependencies netifaces and systemd-manage and try to run usage example:
```
Traceback (most recent call last):
  File "wifi.py", line 2, in <module>
    from wificontrol import WiFiMonitor, WiFiControl
  File "build/bdist.linux-armv6l/egg/wificontrol/__init__.py", line 3, in <module>
  File "build/bdist.linux-armv6l/egg/wificontrol/wifimonitor.py", line 42, in <module>
ImportError: No module named daemon_tree
```
I cannot found any similar named package daemon_tree.
What else is needed?

Best regards,
Nic

**Comment by x42en** [comment]
+1

**Comment by jmachuca77** [comment]
Seems daemon_tree module is still not open sourced (found it on reach). I'd suggest using the previous release 0.4.0 until the module is open sourced or a work around implemented.

**Comment by Nic2012** [comment]
I am not a Python pro, could y give an advise how can we install this release 0.4.0?
Thanks,
Nic

**Comment by patrislav1** [comment]
I [created a fork based on 0.5.0](https://github.com/patrislav1/pywificontrol) which doesn't depend on daemon_tree
(removed the wifimonitor and wifireconnect daemons)
